{
  "props": [],
  "components": {
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 656.0,
      "y": 304.0,
      "props": {
        "title": "Выберите папку для сохранения файла",
        "inputNode": "",
        "actionNode": ""
      }
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 544,
      "y": 240,
      "props": {
        "initialDirectory": "",
        "initialFileName": "Choose file",
        "filterName": "Все файлы",
        "filterExtensions": "*.*",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}