{
  "props": [],
  "components": {
    "dirChooser": {
      "type": "script\\DirectoryChooserScript",
      "x": 192.0,
      "y": 32.0,
      "props": {
        "title": "Выбери папку для сохранения",
        "inputNode": "",
        "actionNode": ""
      }
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 48,
      "y": 16,
      "props": {
        "filterName": "Все файлы",
        "filterExtensions": "*.*",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}